name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tidy:
    name: Go Mod Tidy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Run go mod tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

  build:
    name: Go Build
    runs-on: ubuntu-latest
    needs: tidy
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Build with Makefile
        run: make build VERSION=${GITHUB_REF##*/}

      - name: Upload built binary
        uses: actions/upload-artifact@v4
        with:
          name: toka-${{ runner.os }}-${{ github.ref_name }}
          path: toka

  test:
    name: Go Test
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Run Tests
        run: go test -v ./...
