name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true
      - run: |
          go mod tidy
          git diff --exit-code go.mod go.sum

  build:
    runs-on: ubuntu-latest
    needs: tidy
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true
      - run: make build VERSION=ci
      - uses: actions/upload-artifact@v4
        with:
          name: toka-ci-binary
          path: toka

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true
      - run: go test -v ./...
